settings:
  cooldown-time: 1
  hardcore: false
team:
  'RED':
    name: RED
    color: '4'
    subteams: {}
    members: []
    spawn-location:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0
      pitch: 0.0
  'BLUE':
    name: BLUE
    color: '1'
    members: {}
    subteams: {}
    spawn-location:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0
      pitch: 0.0
  'YELLOW':
    name: YELLOW
    color: 'e'
    members: []
    subteams: {}
    spawn-location:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0
      pitch: 0.0
  'GREEN':
    name: GREEN
    color: '2'
    members: []
    subteams: {}
    spawn-location:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0
      pitch: 0.0

